apiVersion: apps/v1
# what kind of resouces is this?
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  # how many identical replicas?
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        # what containers should be in this pod?
        - image: ghcr.io/eficode-academy/quotes-flask-frontend:release
          name: quotes-flask-frontend
          ports:
            - containerPort: 5000
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # how many resouces should be reserved for this instance?
          resources:
            requests:
              cpu: 1
              memory: 1000Mi
