apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "m5.xlarge", "m5.2xlarge", "m5.4xlarge"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
  limits:
    resources:
      cpu: 6k
  ttlSecondsAfterEmpty: 30
  provider:
    subnetSelector:
      karpenter.sh/discovery: zh-demo-k8s-cluster
    securityGroupSelector:
      karpenter.sh/discovery: zh-demo-k8s-cluster
    tags:
      karpenter.sh/discovery: zh-demo-k8s-cluster
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 40Gi
          volumeType: gp2
          encrypted: false
          deleteOnTermination: true
