apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multitool
  name: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multitool
    spec:
      containers:
        - image: ghcr.io/eficode-academy/network-multitool
          name: network-multitool
          ports:
            - containerPort: 80
          resources: {}
status: {}
